# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

updates:
  - directory: /
    ignore:
      - dependency-name: husky
        versions:
          - ">=5.0.0"
    package-ecosystem: npm
    schedule:
      interval: monthly
    target-branch: develop

version: 2
